sudo: false
language: python
python:
- 2.7
- 3.6
install:
- pip install tox "setuptools>=28.2"
script:
- tox
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.6
  user: jaraco
  distributions: dists
  skip_upload_docs: true
  password:
    secure: IlxH6Vp2Y6XZVaL0e+09LTUOkRRpf5+GpGgkb/VXypZ2V9EfICfDKYtlnGiTOzCxZ6M9JbPySZaD68tSJralkcg5Ki/bWsLc5bBX3hdJykR72BIrc1Tvw7d3IpL1ziDmfN8u80skv7pfOgF0aRu1oS531tdoMJX6wBvmsexp7+bEQbo+9suh8hW0tANd94oJU/Z6VgM0vmxHEior2wSQtTc3v+viNDoq9J9cUoflGVAgynIrTDoGOnSRxj4wcZNckDjRz/1uqVcRuQA+eWw7E16T2PM9QfBW7+KMuHfJnv7VrjjKDutHuR1c9IP6M0W5ahMXVhGfgVfwlquhicAKfNHhhWmeFTE7cQvqac6Hxr/lQPkbIyQ+esbzqtaWueVFLPxP/oI3poXkbF/skHAKEdxUKisCYt+BMZ88tUghSDxuVT9u25Pv79IwcdDLLwFR8NAEraG2WQjFobWY7xB3Pxk8bhAsuj8EpA+CAhfZgC+UwObYrPWUUBaHrtQKKUidjn7i/HpCHcrK7llGf5wYn0IA9HXVY3T0oOTRGsgSr6bZXZcXAVF1ZjVjP7EbVr3kDXCgBrjOerBgl5/Oh2FJ72APRgEuWCtgIzICIqoFpfTf95pUdkefDm0SMYPqdU/JgYqekMavt1wmO/sOYjG+701fM6FW2IncIhDRoWLrJmw=
notifications:
  slack:
    secure: IWQ7gapAxjeijpvg6NYTthH5OZprcFz+YeoVboTbONxeVvsa7zpExyv+u/rtRRmcM3ypx0vaOT04cy804GXGKcjnzWVrZWROpqG4P2os3Ojct4rbWl3PnTBGvLmbC7JckLMI7uOgQyW4Odp5kTAjujB2N4oV6sJgm2UtWlHOTkYclipbgHahs9EJ1jWDspOvGon5gnevFcc4U+rgZZGJ+mm/zvJwHleSk7leiRxGsP0ajnUB/mee5mZKmZFcsOna2bvW8xYaJ38xNaUNyo0LWrEYEfyKyiXJiuoqif1YQQoCo4UkkTAjuANUBd343CHFNoUi0Dojo84BESUJlE58e3bwFCM7Ku4/XCmaWeDLt/8HfdtRu6kGLUQGzc8qyB2LMtTqC86JX13zxE9M8Jd1mcjKD1oCXQlX1udecbdN+2uYbEXL2XQ5rJaCv/3F7F028+Tuuc6gi6F0BPytMAleVuy4hEviQ2tG1UTi9z93ZlY5b9/JVFR5Wm3GaxG0uCiL+zGC0LyE/WfHvYlMqu5xiuienbeEznU2ET0bvMF59IeKkk0D7YMEiTz2nrRAdHq7+q69HZ4LJ6Q8mDLkcWApwrBdcUKxVwJCsqVOezyhy26Jco48+GrKdfQPGo/L2OvadimJs2uduJq4HkIy/muVOPxp3qvHa60ypdq5HPuj2SY=
